"""estado de entidad emisora para revocacion

Revision ID: 23af004e9f72
Revises: 7624c33a5ea6
Create Date: 2026-09-22 12:28:13.943634
"""
from alembic import op
import sqlalchemy as sa


revision = '23af004e9f72'
down_revision = '7624c33a5ea6'
branch_labels = None
depends_on = None

# A diferencia de CREATE TABLE, ALTER TABLE ADD COLUMN no crea el tipo ENUM de Postgres
# por si solo: hay que crearlo (y borrarlo) explicitamente (ver e2a9cbf3dff8, cc0f8f82e2b8).
estado_entidad_emisora = sa.Enum('ACTIVA', 'REVOCADA', name='estado_entidad_emisora')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    estado_entidad_emisora.create(op.get_bind(), checkfirst=True)
    op.add_column('entidad_emisora', sa.Column('estado', estado_entidad_emisora, server_default='ACTIVA', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entidad_emisora', 'estado')
    estado_entidad_emisora.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
