"""firmante y fecha de firma en documento (CU-09)

Revision ID: 34872e77156f
Revises: 23af004e9f72
Create Date: 2026-09-22 16:43:12.440239
"""
from alembic import op
import sqlalchemy as sa


revision = '34872e77156f'
down_revision = '23af004e9f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documento', sa.Column('firma_firmante', sa.String(length=255), nullable=True))
    op.add_column('documento', sa.Column('firma_fecha', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documento', 'firma_fecha')
    op.drop_column('documento', 'firma_firmante')
    # ### end Alembic commands ###
