"""respuesta y actualizacion de autenticacion en documento

Revision ID: 5c0c6c0d198a
Revises: 33821f14aa49
Create Date: 2026-09-19 20:28:51.654043
"""
from alembic import op
import sqlalchemy as sa


revision = '5c0c6c0d198a'
down_revision = '33821f14aa49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documento', sa.Column('respuesta_centralizador', sa.Text(), nullable=True))
    op.add_column('documento', sa.Column('autenticacion_actualizada_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documento', 'autenticacion_actualizada_en')
    op.drop_column('documento', 'respuesta_centralizador')
    # ### end Alembic commands ###
