"""entidad emisora para CU-13

Revision ID: 7624c33a5ea6
Revises: cc0f8f82e2b8
Create Date: 2026-09-22 12:04:31.678565
"""
from alembic import op
import sqlalchemy as sa


revision = '7624c33a5ea6'
down_revision = 'cc0f8f82e2b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidad_emisora',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidad_emisora_api_key_hash'), 'entidad_emisora', ['api_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entidad_emisora_api_key_hash'), table_name='entidad_emisora')
    op.drop_table('entidad_emisora')
    # ### end Alembic commands ###
