"""password_hash nullable para transferencia entrante

Revision ID: af4dacec23fc
Revises: 5c0c6c0d198a
Create Date: 2026-09-21 20:34:59.713443
"""
from alembic import op
import sqlalchemy as sa


revision = 'af4dacec23fc'
down_revision = '5c0c6c0d198a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ciudadano', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ciudadano', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
