"""origen del ciudadano: registro directo o transferencia

Revision ID: b1fb337fb116
Revises: 34872e77156f
Create Date: 2026-09-24 17:32:25.189650
"""
from alembic import op
import sqlalchemy as sa


revision = 'b1fb337fb116'
down_revision = '34872e77156f'
branch_labels = None
depends_on = None

# A diferencia de CREATE TABLE, ALTER TABLE ADD COLUMN no crea el tipo ENUM de Postgres
# por si solo: hay que crearlo (y borrarlo) explicitamente (ver e2a9cbf3dff8, 23af004e9f72).
# Nullable, sin server_default: los ciudadanos que ya existen quedan con origen=NULL
# ("desconocido" en la consola, nunca adivinado) -- ver app.models.Ciudadano.origen.
origen_ciudadano = sa.Enum('REGISTRO_DIRECTO', 'TRANSFERENCIA', name='origen_ciudadano')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    origen_ciudadano.create(op.get_bind(), checkfirst=True)
    op.add_column('ciudadano', sa.Column('origen', origen_ciudadano, nullable=True))
    op.add_column('ciudadano', sa.Column('origen_confirm_api', sa.String(length=500), nullable=True))
    op.add_column('ciudadano', sa.Column('origen_operador_id', sa.String(length=64), nullable=True))
    op.add_column('ciudadano', sa.Column('origen_operador_nombre', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ciudadano', 'origen_operador_nombre')
    op.drop_column('ciudadano', 'origen_operador_id')
    op.drop_column('ciudadano', 'origen_confirm_api')
    op.drop_column('ciudadano', 'origen')
    origen_ciudadano.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
