"""outbox tomado_en para recuperar filas colgadas

Revision ID: bf12d8e39f80
Revises: af4dacec23fc
Create Date: 2026-09-21 22:10:57.598840
"""
from alembic import op
import sqlalchemy as sa


revision = 'bf12d8e39f80'
down_revision = 'af4dacec23fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('tomado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'tomado_en')
    # ### end Alembic commands ###
