"""carpeta completa: notificacion, estado y sustitucion de documento

Revision ID: cc0f8f82e2b8
Revises: fd043ee0d7ed
Create Date: 2026-09-22 11:22:11.901714
"""
from alembic import op
import sqlalchemy as sa


revision = 'cc0f8f82e2b8'
down_revision = 'fd043ee0d7ed'
branch_labels = None
depends_on = None

# A diferencia de CREATE TABLE, ALTER TABLE ADD COLUMN no crea el tipo ENUM de Postgres
# por si solo: hay que crearlo (y borrarlo) explicitamente (ver e2a9cbf3dff8).
estado_documento = sa.Enum('ACTIVO', 'REEMPLAZADO', 'ELIMINADO', name='estado_documento')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ciudadano_id', sa.BigInteger(), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('leida_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadano.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_ciudadano_id'), 'notificacion', ['ciudadano_id'], unique=False)
    op.create_index(op.f('ix_notificacion_creado_en'), 'notificacion', ['creado_en'], unique=False)
    op.drop_constraint('autorizacion_documento_id_fkey', 'autorizacion', type_='foreignkey')
    op.create_foreign_key(None, 'autorizacion', 'documento', ['documento_id'], ['id'], ondelete='CASCADE')
    estado_documento.create(op.get_bind(), checkfirst=True)
    op.add_column('documento', sa.Column('estado', estado_documento, server_default='ACTIVO', nullable=False))
    op.add_column('documento', sa.Column('sustituye_a_id', sa.Uuid(), nullable=True))
    op.add_column('documento', sa.Column('purgar_despues_de', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documento_sustituye_a_id'), 'documento', ['sustituye_a_id'], unique=False)
    op.create_foreign_key(None, 'documento', 'documento', ['sustituye_a_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documento', type_='foreignkey')
    op.drop_index(op.f('ix_documento_sustituye_a_id'), table_name='documento')
    op.drop_column('documento', 'purgar_despues_de')
    op.drop_column('documento', 'sustituye_a_id')
    op.drop_column('documento', 'estado')
    estado_documento.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'autorizacion', type_='foreignkey')
    op.create_foreign_key('autorizacion_documento_id_fkey', 'autorizacion', 'documento', ['documento_id'], ['id'])
    op.drop_index(op.f('ix_notificacion_creado_en'), table_name='notificacion')
    op.drop_index(op.f('ix_notificacion_ciudadano_id'), table_name='notificacion')
    op.drop_table('notificacion')
    # ### end Alembic commands ###
