"""transferencia ciudadano_id nullable on delete set null

Revision ID: de098854465b
Revises: bf12d8e39f80
Create Date: 2026-09-22 02:05:23.393268
"""
from alembic import op
import sqlalchemy as sa


revision = 'de098854465b'
down_revision = 'bf12d8e39f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transferencia', 'ciudadano_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('transferencia_ciudadano_id_fkey', 'transferencia', type_='foreignkey')
    op.create_foreign_key(None, 'transferencia', 'ciudadano', ['ciudadano_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transferencia', type_='foreignkey')
    op.create_foreign_key('transferencia_ciudadano_id_fkey', 'transferencia', 'ciudadano', ['ciudadano_id'], ['id'])
    op.alter_column('transferencia', 'ciudadano_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
