"""email_carpeta nullable para PENDIENTE_VERIFICACION

Revision ID: de850422e354
Revises: c6336c116d63
Create Date: 2026-09-19 17:50:18.438165
"""
from alembic import op
import sqlalchemy as sa


revision = 'de850422e354'
down_revision = 'c6336c116d63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ciudadano', 'email_carpeta',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ciudadano', 'email_carpeta',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
