"""token de primer acceso para ciudadano recibido por transferencia

Revision ID: fd043ee0d7ed
Revises: de098854465b
Create Date: 2026-09-22 03:30:36.961543
"""
from alembic import op
import sqlalchemy as sa


revision = 'fd043ee0d7ed'
down_revision = 'de098854465b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciudadano', sa.Column('token_primer_acceso_hash', sa.String(length=64), nullable=True))
    op.add_column('ciudadano', sa.Column('token_primer_acceso_vence_en', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'ciudadano', ['token_primer_acceso_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ciudadano', type_='unique')
    op.drop_column('ciudadano', 'token_primer_acceso_vence_en')
    op.drop_column('ciudadano', 'token_primer_acceso_hash')
    # ### end Alembic commands ###
